# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
