# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0004_auto_20160330_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='summary',
        ),
    ]
