# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0005_auto_20160331_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
